### PR TITLE
fix: compatibility with GCC <10

### PR DESCRIPTION
**Pull request by mmyjona**
## What does this PR address?

this pr fix the compile error when compile on debian 11, gcc version 10.2.1 with bazel.
the error is:
`src/whispercpp/context.cc:26:39: error: 'class std::basic_ostream<char>' has no member named 'str'`

## Before submitting:

- [ x ] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
      guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request.
- [ x ] Did you read through and follow [development guidelines](../DEVELOPMENT.md)?
- [  ] Did your changes require updates to the documentation? Have you updated those accordingly?
- [  ] Did you write tests to cover your changes?

### CODE REVIEW

**Review by aarnphm — COMMENTED** [review]
LGTM. Once the test pass I will merge this in and release a new version

**Review by aarnphm — APPROVED** [review]
Thanks.
